INSERT INTO [CONTACT](NAME) VALUES ('CONTACT A');
INSERT INTO [CONTACT](NAME) VALUES ('CONTACT B');
INSERT INTO [CONTACT](NAME) VALUES ('CONTACT C');

INSERT INTO [GROUP](NAME) VALUES ('GROUP A');
INSERT INTO [GROUP](NAME) VALUES ('GROUP B');
INSERT INTO [GROUP](NAME) VALUES ('GROUP C');

INSERT INTO [ITEM](NAME,GROUPID) VALUES ('GROUP A ITEM 1',1);
INSERT INTO [ITEM](NAME,GROUPID,TAGNAME1) VALUES ('GROUP A ITEM 2',1,'TAG A2');
INSERT INTO [ITEM](NAME,GROUPID) VALUES ('GROUP A ITEM 3',1);

INSERT INTO [ITEM](NAME,GROUPID) VALUES ('GROUP B ITEM 1',2);
INSERT INTO [ITEM](NAME,GROUPID,TAGNAME2) VALUES ('GROUP B ITEM 2',2,'TAG B2');
INSERT INTO [ITEM](NAME,GROUPID) VALUES ('GROUP B ITEM 3',2);

INSERT INTO [ITEM](NAME,GROUPID) VALUES ('GROUP C ITEM 1',3);
INSERT INTO [ITEM](NAME,GROUPID,TAGNAME3) VALUES ('GROUP C ITEM 2',3,'TAG C2');
INSERT INTO [ITEM](NAME,GROUPID) VALUES ('GROUP C ITEM 3',3);

SELECT * FROM [CONTACT]
SELECT * FROM [GROUP]
SELECT * FROM [ITEM]
